### ISSUE TITLE
Planet Xamarin App

### ISSUE THREAD

**Issue by luismts** [planetxamarin/planetxamarin#489]
Is it possible that I can contribute by making the app for Planet Xamarin as a contribution? I am creating a community of Xamarin in the Dominican Republic and I would like to create with them the base of the application for Planet Xamarin, open source of course.

**Comment by jfversluis** [comment]
Would this app be released in the store? How do you want to set it up? Will it be a simple WebView? Since we don't expose any API endpoints etc.

Personally, I don't really see any added value in a Planet Xamarin app as-is, but as a sample app to be built for learning purposes it could be nice. What I would like to avoid is having the app released to the app store and people think it came from here. Then I see a lot of issues coming this way with wishes, feature requests and bugs etc.

**Comment by luismts** [comment]
Yes, I would be in the store, so the community could stay a little more updated directly. And no, it would be a few pages with several listviews, a little razor to show the HTML content and maybe a list with the authors and their links to their pages (a simple card like on the planet xamarin page). All this will be based on the same guidelines that the page have.

Some things I want to set up in the application are:

* Razor
* Background services
* Notifications
* Deep Linking
* Offline mode
* Etc...

I can see your concern, however, we can clarify this point within the application and in the project. We would keep it with the basic needs for the moment.

**Comment by luismts** [comment]
@jfversluis Any response to this topic?

**Comment by Cheesebaron** [comment]
I agree with @jfversluis. I don't see the big value for Planet Xamarin for this. Planet Xamarin is just a RSS feed, where people can use whatever client to read that feed. However, please don't have us decide whether you do this or not.

We would however ask that you do not use the Planet Xamarin name for the app. You are allowed to use our data source as it is publicly available under the MIT license as stated in the LICENSE file.

**Comment by luismts** [comment]
@Cheesebaron thanks for your answer. I gonna use another name for the app. But in any case, what about the API endpoints?

I mean as a @jfversluis said you don't expose any API endpoints and would be really cool if you gave us a way to consume a feed about the authors or searches in the posts. Can be this possible?

**Comment by jfversluis** [comment]
I think what we're trying to say is: we can't forbid you to do it, but it doesn't really have any added value for us. That may sound really negative, I'm sorry about that, I'm all for learning by doing, but in this case, we can't support you with it.

The source is open, you can fork it and host it yourself if you want. You can add the endpoints yourself, heck. Make an exercise out of that!

At this point, we're not going to add the endpoints in our repo since it doesn't do anything for us except introduce complexity. We aim to be a simple aggregator and I think we're really complete right now. I'd love to see anything you come up with, but don't expect any effort from us on this. Sorry 🙂

**Comment by luismts** [comment]
Ok, I see. I will try to do something on my own, thanks! 🙂
