### ISSUE TITLE
I cannot find my blog in website

### ISSUE THREAD

**Issue by jessejiang0214** [planetxamarin/planetxamarin#582]
**Describe the bug**
I saw the main already merged my PR 0c98525bc0e5ec1b62c85de2445c3bc437550383
But I post a blog last night, I cannot see it in today RSS.

Please help me to fix it.
Thanks,
Jesse

**Comment by nickrandolph** [comment]
Wait 24 hours to see if it appears.

**Comment by jfversluis** [comment]
Are you talking about the App Center one? As per the default filter, there should be Xamarin in the title, in one of the categories of as a keyword and from what I can see there is no Xamarin in either of these for that post

**Comment by jessejiang0214** [comment]
Hi @nickrandolph good to see you here, how's going?

**Comment by jessejiang0214** [comment]
Hi @jfversluis , well our project in App Centre and DevOps is Xamarin. I just forget to mention it. Cause in my mind ```string MobileApp = "Xamarin" ``` it's by default. I did some changes in my blog.

**Comment by jfversluis** [comment]
I understand where you're coming from and if the focus is Xamarin then it's fine by me.

To be clear, it's not something I'm saying because I don't agree with the content, it's just a couple of things we built in order to get the closest thing to Xamarin specific content. You can see it here: https://github.com/planetxamarin/planetxamarin/blob/master/src/Firehose.Web/Extensions/SyndicationItemExtensions.cs#L8

We check a post on the three things mentioned earlier: title, category, and keywords and if one of those contains Xamarin then it should be good. In addition, you could implement the `IFilterMyBlogPosts` to create a custom filter.

Looking at your last App Center post there is no Xamarin in the title, the category is "unspecified" and I don't see any keywords tag so that is why it didn't show up in the feed.

**Comment by jfversluis** [comment]
I'm assuming you have enough information to get you going to resolve this, therefore closing this issue.
