### ISSUE TITLE
Twitter account not posting blog post

### ISSUE THREAD

**Issue by roubachof** [planetxamarin/planetxamarin#651]
The @PlanetXamarin Twitter account is not posting any planet xamarin blog since march 5th.
It's maybe related to #650.

**Comment by Cheesebaron** [comment]
@jamesmontemagno do we have a limit of how much memory we can use for caching results? It seems like when refreshing the feed or preview the cache is having some issues. So it fetches all the feeds again to combine.

Running PlanetXamarin locally, this caching works fine and refreshing the page after initial fetch, it doesn't reload all the feeds.

I think this might be throwing off the Twitter bot, because when it tries to get the feed it might be thinking the feed is timing out

**Comment by jamesmontemagno** [comment]
So, it used to ping http://www.planetxamarin.com/feed?lang=en

which doesn't existing anymore in the new code.

**Comment by jamesmontemagno** [comment]
The feed does seem to take a very long time. Are we caching locally for X time or are we hitting every URL every single time?

**Comment by Cheesebaron** [comment]
@jamesmontemagno we are using Polly Memory Cache which works fine locally.

Hitting the URL you posted works, but returns an empty feed. I will look into that issue.

**Comment by jamesmontemagno** [comment]
Hmmmm, whenever I go to https://www.planetxamarin.com/feed it takes a long long time.

If I try to update IFTTT it will fail because it is taking to long to load.

Right now I just did it and it took about 1 full minute to load.

Compared to: https://soundbite.fm/rss which is the old blog monster for mine and that has 500+ entries

**Comment by Cheesebaron** [comment]
@jamesmontemagno running locally is taking 15 sec or so for me. While the Azure instance we are running seems to be significantly slower.

Also soundbite.fm... Of course it will be faster, it is only fetching from 5 feeds, even without cache it will be quick.

I've tried improving the cache in the linked PR. As I've said the caching has always been working locally when running with debug here. However, something is up when it is deployed to Azure.

**Comment by Cheesebaron** [comment]
I just randomly sampled going on the webpage to grab the feed. It responded instantly. Looks like my PR might have helped the caching issue!

**Comment by jamesmontemagno** [comment]
And tweets are going :)
