### ISSUE TITLE
ITT we talk about design

### ISSUE THREAD

**Issue by ghuntley** [planetxamarin/planetxamarin#7]

**Comment by ghuntley** [comment]
I think the design is good enough to soft-launch. It can be evolved as we go via PR. If anyone has a designer in their family @martijn00 (your sister?) and has the time to help out there that would be neat.

![image](https://cloud.githubusercontent.com/assets/127353/21968359/ff512240-dbe7-11e6-9c64-9c5152277a6b.png)
![image](https://cloud.githubusercontent.com/assets/127353/21968371/202f16d4-dbe8-11e6-95a6-a509c219405a.png)

**Comment by jamesmontemagno** [comment]
Ship It

**Comment by jfversluis** [comment]
I now notice it says Xamarin Planet everywhere, it is Planet Xamarin, right?

**Comment by ghuntley** [comment]
@jfversluis this has since been fixed. As per https://www.xamarin.com/branding we are not allowed to prefix with Xamarin (as much as I would love to do so with WeeklyXamarin)

**Comment by Cheesebaron** [comment]
Can we make the menu bar a bit bigger, I think the logo looks a bit cramped up there. Same size as the Xamarin page would be better I think.

Not sure if it is too pink/purple.

**Comment by tirzavdijk** [comment]
The design looks pretty decent as far as I can judge from the screenshots. However I do think that with a couple of changes it could look a lot more refined. Made a list of things that I noticed after having a look at the screenshots.

- Agree with @Cheesebaron that the logo can use a bit more space around it. Good idea to use the same height as Xamarin. 
- The purple color is one of Xamarin's brand colors, so the color does make sense. I would use it very sparingly in other places. Because it is currently used for the titles and links it can get a bit overwhelming. 
- Alignment of text and elements could be improved a lot. I'm seeing a lot of inconsistencies.
- Font sizes / colors / weights are inconsistent and don't really bring attention to the most important elements. 
- And the design would really benefit from a better use of whitespace. A lot of elements are either really close to each other or strangely far apart. 

Hope this helps! Just let me know if you have further questions. 😄

**Comment by ghuntley** [comment]
Discussion for this has forked and is taking place in #planetxamarin on XamarinChat. Come join us.
